### ISSUE TITLE
Sort by date issue

### ISSUE THREAD

**Issue by opensecure** [dulldusk/phpfm#10]
Sort by date is not accurate for AM and PM files date.

**Comment by dulldusk** [comment]
Thanks for the notice! I will fix that.

**Comment by dulldusk** [comment]
I could not reproduce the problem. Please send a screenshot here.

**Comment by opensecure** [comment]
It is not sort correctly for files created during morning and afternoon times.
As I checked, the line 2193 can change to below to solve it:

$entry_list[$entry_count]["time"] = date("His", filemtime($fm_current_dir.$entry));

**Comment by dulldusk** [comment]
Very nice! Just commited the change. 
I even looked at this exact line before, but did not see the problem at first glace.
