### ISSUE TITLE
Readonly Mode

### ISSUE THREAD

**Issue by maxmont** [dulldusk/phpfm#12]
Congratulation for this great job.
Would it be possible to have a readonly mode with a dedicated password?
Thanks

**Comment by dulldusk** [comment]
Hi maxmont. If you have root access to your server, you can set a password on phpFileManager, and then change its owner to root, and permissions to 644. That way, the script ans it´s configuration will not be able to be modified by itself anymore, attaining the readonly mode you are looking for.

**Comment by dulldusk** [comment]
But if you want to allow other persons to use it, you will have do ensure they cannot upload or remane files using the script, with php extension. And block system exec functions too. And configure open_basedir on php.ini or on the virtualhost using "php_admin_value open_basedir".
