### ISSUE TITLE
Cannot paste in shell window

### ISSUE THREAD

**Issue by opensecure** [dulldusk/phpfm#23]
We cannot paste a command directory to the shell window, so I have to write it down again manually and it is taking time plus mistyping problem.

**Comment by dulldusk** [comment]
This is very strange. Copy/Paste works on IE, Firefox and Chrome. What browser are you using?

**Comment by opensecure** [comment]
For your information, since I update my macOS to Catalina, I can copy and paste and it is no problem in source code.
