### ISSUE TITLE
Unclear on permissions

### ISSUE THREAD

**Issue by veeectorm** [dulldusk/phpfm#29]
So this thing works like a charm. From what i gather, it does everything (and more than) i need.
Im wondering what permissions need to be for it to work correctly at least on my case. Im a newbie. Password wont save, i cant upload nor delete files, so i imagine this is related to permissions of lighttpd.

Thanks for the help!

V.

**Comment by dulldusk** [comment]
Hi veeectorm. It´s not an issue, is really just about permissions on your server.
Access your phpfm and click on shell button. It will show what user your lighttpd is using to run the script. That same user, must have permition to write on the files and folders.
