### ISSUE TITLE
Impossible to download big files with size >  of PHP memory_limit or RAM size

### ISSUE THREAD

**Issue by acca** [dulldusk/phpfm#31]
If I try to download a file which is bigger in size than PHP `memory_limit` i got this error: 

`PHP Fatal error:  Allowed memory size of XXXXXXX bytes exhausted (tried to allocate XXXXXXXX bytes) in PATH/index.php on line 921`

The motivation could be that `fpassthru($fh);` on line 921 loads the full the file in memory resulting in exhausted memory due to ` memory_limit` settings or size of server's RAM memory.

**Comment by dulldusk** [comment]
Thanks for the solution!
