### ISSUE TITLE
Call to undefined function get_magic_quotes_gpc() 

### ISSUE THREAD

**Issue by MEGAMINDMK** [dulldusk/phpfm#47]
`Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in C:\xampp\htdocs\index.php:135 Stack trace: #0 {main} thrown in C:\xampp\htdocs\index.php on line 135`
occured after i downloaded the latest [xampp](https://www.apachefriends.org/index.html) with [php v8.0.3 ](https://windows.php.net/download#php-8.0)

**Comment by ncovercash** [comment]
This seems to still be an issue - why did you close?

**Comment by arnisjuraga** [comment]
Function `get_magic_quotes_gpc` is removed from PHP 8 (https://www.php.net/manual/en/function.get-magic-quotes-gpc.php).

Please check this PR https://github.com/dulldusk/phpfm/pull/40 . FIX for PHP 8 (removed `get_magic_quotes_gpc` function) is merged, may be You can update to latest master branch?

**Comment by MEGAMINDMK** [comment]
> 
> 
> This seems to still be an issue - why did you close?

bcz the fix was already implemented but not updated in main branch

**Comment by ncovercash** [comment]
Gotcha, thanks. I was going based off of the latest NPM version (might be a good idea to push)

**Comment by Pipin-5aragih** [comment]
i know its one year after this issue posted, 
i find this occur to one of my code, here i did
update the npm then just delete the  get_magic_quotes_gpc() lines of code.
and thats it
