### ISSUE TITLE
File tree view is not loading

### ISSUE THREAD

**Issue by prasathmani** [dulldusk/phpfm#5]
File tree view is not loading and I'm getting error following error.
Tested in : Chrome Version 71.0.3578.98
![image](https://user-images.githubusercontent.com/11345598/51842342-a8e07800-2336-11e9-8425-6e27c594b5af.png)

*updating new version `jstree` might solve the problem

**Comment by dulldusk** [comment]
It is linux related, i just reproduced the error. Will fix asap. Thanks!
