### ISSUE TITLE
PHPFM not compatible with php v8

### ISSUE THREAD

**Issue by sultank1** [dulldusk/phpfm#53]
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home//vel.com/phpfm_1.7.9.php:2389 Stack trace: #0 /home/vel.com/phpfm_1.7.9.php(5534): dir_list_form() #1 /home/vel.com/phpfm_1.7.9.php(603): frame3() #2 {main} thrown in /home/vel.com/phpfm_1.7.9.php on line 2389

**Comment by tdi2004** [comment]
Still not working with PHP 8.0.11 / 8.0.12 / 8.1.0

**Comment by tdi2004** [comment]
workaround: tinyfilemanager.php is an appropriate alternative.
