### ISSUE TITLE
How to set password

### ISSUE THREAD

**Issue by ccpplinux** [dulldusk/phpfm#66]
How to set password in this script? In which line number I need to set the password? In which variable I need to set the password? Please clarify it.

**Comment by MisterDuval** [comment]
with the configuration button, you can set the password

**Comment by ccpplinux** [comment]
Thanks for reply. Now I have set the password through Config button. One thing more. How to change the font size of editor? In which variable the font size is stored?

**Comment by MisterDuval** [comment]
no font size change, use you browser zoom

**Comment by ccpplinux** [comment]
I changed the value of fontSize variable at line 3941 in index.php and the font size of editor is now changed. One thing more as you are using Ace editor but auto completion feature of Ace editor is not working. So can you please tell me how to enable auto completion feature of Ace editor?

**Comment by MisterDuval** [comment]
please, this is not a forum, you can close the issue
