### ISSUE TITLE
Cannot close popup windows

### ISSUE THREAD

**Issue by opensecure** [dulldusk/phpfm#7]
When I open popup windows(Server Info, Shell, Portscan, About or Edit) , the positions are too up as its close link hide under browser window and I cannot close the popup window without refresh the page. I checked it in Safari, Chrome, Opera, Firefox in MacOS also in Microsoft Edge on windows, all have the same problem. It possible to fix by one of three below solutions:
1- Change line 1459 to "top: 60%;"
2- Change line 1461 to "transform: translate(-50%, -40%);"
3- Change line 1459 to "top: 0;" and line 1461 to "transform: translate(-50%, 0);"

**Comment by dulldusk** [comment]
I plan to add resizable modal windows on the next release. But since you posted the bug and a simple solution, I made some changes and commited a here on github. Thanks!

**Comment by opensecure** [comment]
Great, also if the modal windows open as float I think it is better work with them.
