### ISSUE TITLE
Config option to restrict access to everything below one folder

### ISSUE THREAD

**Issue by chr15m** [dulldusk/phpfm#8]

**Comment by dulldusk** [comment]
It´s there already. Just set the File Manager Root.

**Comment by chr15m** [comment]
@dulldusk great, thanks.

I was that this configuration is stored in a comment at the top of the file after you hit save:

```php
//{"lang":"","fm_root":"\/var\/www\/blah","timezone":"","date_format":"Y\/m\/d H:i","auth_pass":"-----XXX-----","error_reporting":1}
```

Is there any documentation on this and which other settings which are stored in that way?

Often people use a script (bash or Ansible etc.) to deploy their PHP applications and in this scenario it's good to configure the app with no human input. For example with Ansible you can use `lineinfile` to add this configuration line to edit.php when deploying.
