### ISSUE TITLE
English miss spelling

### ISSUE THREAD

**Issue by opensecure** [dulldusk/phpfm#9]
“items” is wrong in  below english lanquage array:
$set[“en”][“NoSel”] = ‘There are no selected itens’;
$set[“en”][“RemSel”] = ‘DELETE selected itens’;

By the way, i want to add “Persian/Dari” translation, but i do not know how to send it to you.

**Comment by dulldusk** [comment]
Hi friend. Thanks for the notice.
You can send me your translation on dulldusk@gmail.com

**Comment by dulldusk** [comment]
Fixed.
